Data Procc

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
#read csv.file
df = pd.read_csv('/content/drive/MyDrive/new drive/DM Projrct/student-mat.csv')
df = pd.read_csv('/content/drive/MyDrive/new drive/DM Projrct/student-por.csv')

In [4]:
# Load datasets
# Use the full path to the files in Google Drive
mat = pd.read_csv("/content/drive/MyDrive/new drive/DM Projrct/student-mat.csv", sep=';')
por = pd.read_csv("/content/drive/MyDrive/new drive/DM Projrct/student-por.csv", sep=';')

# Add a new column to identify the course
mat["course"] = "Math"
por["course"] = "Portuguese"

# Combine them
combined = pd.concat([mat, por], ignore_index=True)

# Save to new CSV
# You can save the combined file to Google Drive as well
combined.to_csv("/content/drive/MyDrive/new drive/DM Projrct/student-combined.csv", index=False)

In [5]:
#head
df.head()

  school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3
0  GP;"F";18;"U";"GT3";"A";4;4;"at_home";"teacher...
1  GP;"F";17;"U";"GT3";"T";1;1;"at_home";"other";...
2  GP;"F";15;"U";"LE3";"T";1;1;"at_home";"other";...
3  GP;"F";15;"U";"GT3";"T";4;2;"health";"services...
4  GP;"F";16;"U";"GT3";"T";3;3;"other";"other";"h...

In [6]:
#describe
df.describe()

       school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3
count                                                 649
unique                                                649
top     MS;"M";18;"R";"LE3";"T";3;2;"services";"other"...
freq                                                    1

In [7]:
#nell value
df.isnull().sum()

school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3    0
dtype: int64